<?php

function profect_form_alter(&$form, &$form_state, $form_id) {

$pos = strpos($form_id, "webform_client_form");
  if ($pos !== FALSE) {
    foreach (element_children($form['submitted']) as $element) {
      if (isset($form['submitted'][$element]['#title']))
        $form['submitted'][$element]['#title'] = t($form['submitted'][$element]['#title']);
    }
    if (isset($form['title']['#title'])) {
      $form['title']['#title'] = t($form['title']['#title']);
    }
    
}
//print_r($form['#id']);

   
 if (isset($form['#node']->type) && ($form['#node']->type == 'webform')) {
if (($form['#id']== 'webform-client-form-23')||($form['#id']== 'webform-client-form-30')){
    foreach ($form["submitted"] as $key => $value) {
      switch ($value["#type"]) {
        case 'textfield':
        case 'textarea':
        case 'webform_email':
          $form["submitted"][$key]['#attributes']["placeholder"] = $value["#title"];
          break;
      } 
    }
  }
}
}
/**
 * Implements hook_node_view().
 */
function profect_node_view($node, $view_mode) {
  // Just make a blog menu item active during viewing blog post detailed page.
  if (!empty($node->type)) {
    if($node->type == 'product'){
      menu_tree_set_path('main-menu', 'Products');
    }
  }
}


    
